[tool.poetry]
name = "django-basics"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
asgiref = "==3.11.0"
black = "==25.12.0"
click = "==8.3.1"
colorama = "==0.4.6"
django = "==6.0"
dotenv = "==0.9.9"
flake8 = "==7.3.0"
isort = "==7.0.0"
librt = "==0.7.7"
mccabe = "==0.7.0"
mypy = "==1.19.1"
mypy-extensions = "==1.1.0"
packaging = "==25.0"
pathspec = "==1.0.0"
pillow = "==12.1.0"
platformdirs = "==4.5.1"
psycopg2 = "==2.9.11"
pycodestyle = "==2.14.0"
pyflakes = "==3.4.0"
python-dotenv = "==1.2.1"
pytokens = "==0.3.0"
sqlparse = "==0.5.5"
typing = "==3.7.4.3"
typing-extensions = "==4.15.0"
tzdata = "==2025.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
